FROM elm_mynode

ARG exercise

ENV exercise=${exercise} \
    PATH="$PATH:/exercism/elm/${exercise}/node_modules/.bin"

COPY post-build.sh /usr/local/bin/post-build.sh

RUN chmod a+x /usr/local/bin/post-build.sh

WORKDIR $exercise

VOLUME /exercism/elm

ENTRYPOINT [ "/usr/local/bin/post-build.sh" ]

CMD elm-test --watch